create ConnectECUTestView
THNGL/capstone_x2ecutest pull request #17
Opened 2023-10-13 15:35 UTC by THNGL

2023-10-16 11:33 UTC, s-gbz requested changes
Schöne Oberfläche, soweit sauberer, schlanker Code!

Schau dir aber bitte nochmal die Duplikationsmeldung (bzw. ob du sie nicht gelöst bekommst) und die paar Anmerkungen meinerseits an

2023-10-16 11:33 UTC, s-gbz commented on frontend/src/main/java/de/iav/frontend/controller/ConnectECUTestViewController.java
> +    Button connectButton;
Denk dran das Kapselungsprinzip von OOP zu berücksichtigen und alle Klassenattribute privat zu setzen
Tipp: Während dem Prozess merkst du auch welche unbenutzt sind (alle außer dem 2. und 3.) - müssen die jetzt in diesem Vertical Slice dann schon hier drin sein??

2023-10-16 11:33 UTC, s-gbz commented on frontend/src/main/java/de/iav/frontend/controller/WelcomePageViewController.java
>      }
So richtig agil ist es vlt. nicht, wenn die gesamte UI quasi schon konstruiert ist, aber nur 1 Seite benutzbar ist.
Naja, das aber einfach mal als Anmerkung ;D

2023-10-16 11:33 UTC, s-gbz commented on frontend/src/main/resources/de/iav/frontend/css/controlButton.css
> +.button {
Gabs nen Grund warum du das gemeinsam geteilte CSS nicht in einer gemeinsamen CSS zusammengefasst hast?
Ist für mich auch fein, bestimmst nutzt man diese indivuelle "Dateiansicht" praktisch im SCeneBuilder, aber auch hier einfach mal als Anstoß.

2023-10-16 11:33 UTC, s-gbz commented on frontend/src/main/resources/de/iav/frontend/fxml/connectECUTestView.fxml
> +<AnchorPane maxHeight="-Infinity" maxWidth="-Infinity" minHeight="-Infinity" minWidth="-Infinity" prefHeight="720.0" prefWidth="1080.0" xmlns="http://javafx.com/javafx/20.0.1" xmlns:fx="http://javafx
Es erscheint die stetige Warnung
`WARNUNG: Loading FXML document with JavaFX API of version 20.0.1 by JavaFX runtime of version 20`. Die kannst du fixen indem du die Version in den .fxml Dateien (`javafx/20.0.1"`) mit der "pom-Version" gleichsetzt.

2023-10-18 09:50 UTC, THNGL commented on frontend/src/main/java/de/iav/frontend/controller/ConnectECUTestViewController.java
> +    Button connectButton;
Hast du recht das ist Quatsch, ich habe das ganze schonmal lokal gemerged deswegen kommen jetzt hier die einzelnen PR's

Habe es aber trotzdem behoben

2023-10-18 09:50 UTC, THNGL commented on frontend/src/main/java/de/iav/frontend/controller/WelcomePageViewController.java
>      }
gleiches Thema wie oben

wurde behoben

2023-10-18 09:51 UTC, THNGL commented on frontend/src/main/resources/de/iav/frontend/css/controlButton.css
> +.button {
habe da ein Stylesheet raus gemacht --> macht jetzt nen schlanken schuh

2023-10-18 09:51 UTC, THNGL commented on frontend/src/main/resources/de/iav/frontend/fxml/connectECUTestView.fxml
> +<AnchorPane maxHeight="-Infinity" maxWidth="-Infinity" minHeight="-Infinity" minWidth="-Infinity" prefHeight="720.0" prefWidth="1080.0" xmlns="http://javafx.com/javafx/20.0.1" xmlns:fx="http://javafx
wenn ich das im Scene Builder bearbeite dann springt das immer wieder zurück

deswegen würde ich das erstmal drin lassen, ich weiß ja woran es liegt

2023-10-18 09:58 UTC, s-gbz approved these changes
Well done ✅

2023-10-18 09:59 UTC, merged